
--DROP DATABASE PROYECTO_CSHARP
--GO 

CREATE DATABASE PROYECTO_CSHARP
GO 


-- Pone en uso una Base datos
USE PROYECTO_CSHARP
GO 




CREATE TABLE USUARIO_ROL
(
	ID INT NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CONSTRAINT PK_USUARIO_ROL_ID PRIMARY KEY(ID)
)
GO 

--DROP TABLE USUARIOS
--GO 
CREATE TABLE USUARIOS (
	
	ID INT NOT NULL,
	USUARIO_ROL_ID INT NOT NULL,
	USUARIO VARCHAR(50) NOT NULL,
	CONTRASENIA NVARCHAR(350) NOT NULL,
	CORREO VARCHAR(100) NULL,
	ACTIVO BIT NOT NULL 
	CONSTRAINT PK_USUARIOS_ID PRIMARY KEY (ID),
	CONSTRAINT FK_USUARIOS_USUARIO_ROL_ID FOREIGN KEY (USUARIO_ROL_ID) REFERENCES USUARIO_ROL(ID)
)
GO 



CREATE TABLE ACCESOS 
(
	ID INT NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	ACTIVO BIT NOT NULL,
	CONSTRAINT PK_ACCESOS_ID PRIMARY KEY(ID)
)
GO 


DROP TABLE IF EXISTS USUARIO_ACCESO_PERMISOS
GO 
CREATE TABLE USUARIO_ACCESO_PERMISOS 
(
	ID INT NOT NULL,
	ACCESO_ID INT NOT NULL,
	USUARIO_ID INT NOT NULL,

	ACCEDER BIT NOT NULL,
	INSERTAR BIT NOT NULL,
	MODIFICAR BIT NOT NULL,
	ANULAR BIT NOT NULL,

	CONSTRAINT PK_USUARIO_ACCESO_PERSMISOS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_USUARIO_ACCESO_PERSMISOS_ACCESO_ID FOREIGN KEY (ACCESO_ID) REFERENCES ACCESOS(ID),
	CONSTRAINT FK_USUARIO_ACCESO_PERSMISOS_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),

)
GO 


CREATE TABLE EMPRESA
(
	NOMBRE VARCHAR(350) NOT NULL,		 -- Nombre de la empresa
	DIRECCION VARCHAR(500) NOT NULL,	 -- direccion 
	TELEFONO VARCHAR(50) NOT NULL,		 -- telefono fijo
	LOGO IMAGE NULL,					 -- Logotipo que aparecera en todos los reportes
	LEMA VARCHAR(350) NULL,				 -- Lema del negocio
	CORREO VARCHAR(100) NULL, 			 -- Correo de Ventas/Servicio al cliente
	SITIO_WEB VARCHAR(100) NULL,		 -- Sitio de web
	RTN VARCHAR(50) NULL,				 -- Registro tributario nacional
	REPRESENTANTE VARCHAR(100)			 -- Nombre del representante legal
)

GO 




CREATE TABLE HISTORIAL_ERRORES
(
	ID INT NOT NULL,
	FECHA_CREACION DATETIME NULL,
	USUARIO_CREACION VARCHAR(50) NULL,
	REGISTRO_ID INT NULL,
	TABLA VARCHAR(100) NULL,
	ACCION INT NULL,
	MSJ_ERROR VARCHAR(1000) NULL,

	CONSTRAINT PK_HISTORIAL_ERRORES PRIMARY KEY (ID)
)



CREATE TABLE HISTORIAL_CAMBIOS
(
	ID INT NOT NULL,
	FECHA_CREACION DATETIME NULL,
	USUARIO_CREACION VARCHAR(50) NULL,
	REGISTRO_ID INT NULL,
	TABLA VARCHAR(100) NULL,
	ACCION INT NULL,
	NOTAS VARCHAR(1000) NULL,

	CONSTRAINT PK_HISTORIAL_CAMBIOS PRIMARY KEY (ID)
)



CREATE TABLE  CORREOS
(
	ID INT NOT NULL,
	FECHA_CREACION DATETIME NULL,
	USUARIO_CREACION VARCHAR(50) NULL,
	REMITENTE VARCHAR(100) NOT NULL,
	ASUNTO VARCHAR(350) NULL,
	MENSAJE NVARCHAR(MAX) NULL,

	CONSTRAINT PK_CORREOS_ID PRIMARY KEY (ID)
)




CREATE TABLE  CORREOS_DETALLE
(
	ID INT NOT NULL,
	CORREO_ID INT NOT NULL,
	FECHA_CREACION DATETIME NULL,
	DESTINATARIO VARCHAR(100),


	CONSTRAINT PK_CORREOS_DETALLE_ID PRIMARY KEY (ID),
	CONSTRAINT FK_CORREOS_DETALLE_CORREO_ID FOREIGN KEY(CORREO_ID) REFERENCES CORREOS(ID)
)



CREATE TABLE PARAMETROS_GENERALES
(
	ID INT NOT NULL,
	DESCRIPCION VARCHAR(100),
	VALOR VARCHAR(100)

)








---------------------------------------------  LOGICA DEL NEGOCIO  ---------------------------------------------------

CREATE TABLE [dbo].[CLIENTES](
	[ID] [int] NOT NULL,
	[IDENTIDAD] [varchar](50) NOT NULL,
	[NOMBRE] [nvarchar](350) NOT NULL,
	[DIRECCION] [nvarchar](500) NULL,
	[TELEFONO] [varchar](50) NOT NULL,
	[CORREO] [varchar](100) NULL,
	[MUNICIPIO] [varchar](100) NOT NULL,
	[FECHA_NACIMIENTO] [date] NULL,
	FECHA_CREACION DATETIME NULL,
	FECHA_MODIFICACION DATETIME NULL,
	USUARIO_CREACION VARCHAR(50) NULL,
	USUARIO_MODIFICACION VARCHAR(50) NULL,
	ACTIVO BIT 
	
	CONSTRAINT  PK_CLIENTES  PRIMARY KEY(ID)
)
GO 


 
 CREATE TABLE CATEGORIAS
 (
	ID INT NOT NULL,
	CATEGORIA VARCHAR(100) NOT NULL, 
	CONSTRAINT PK_CATEGORIAS_ID PRIMARY KEY(ID)
 )

 GO


 --DROP TABLE SERVICIOS
 --GO 
CREATE TABLE SERVICIOS
(
	ID INT NOT NULL,						 -- 
	CATEGORIA_ID INT NOT NULL,				 -- 
	FECHA_CREACION DATETIME NULL,			 -- 
	FECHA_MODIFICACION DATETIME NULL,		 -- 
	USUARIO_CREACION VARCHAR(50) NULL,		 -- 
	USUARIO_MODIFICACION VARCHAR(50) NULL,	 -- 
	CODIGO VARCHAR(50) NOT NULL,			 -- 
	DESCRIPCION VARCHAR(100) NOT NULL,		 -- 
	VALOR_INICIAL DECIMAL (15,2) NOT NULL,	 -- 
	VALOR DECIMAL (15,2) NOT NULL,			 -- 
	ACTIVO BIT NOT NULL,					 -- 
	CALCULA_VALOR VARCHAR(50) NOT NULL		 -- Determina la forma del calculo ("FIJO", "VARIABLE")

	CONSTRAINT PK_SERVICIOS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_SERVICIOS_ID_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID)
)

GO






--DROP TABLE SERVICIO_CUENTAS
--GO 
CREATE TABLE SERVICIO_CUENTAS 
(
	ID INT NOT NULL,					  -- 
	SERVICIO_ID INT NOT NULL,			  -- 
	CLIENTE_ID INT NOT NULL,			  -- 
										  -- 
	FECHA_CREACION DATETIME NULL,		  -- 
	FECHA_MODIFICACION DATETIME NULL,	  -- 
	USUARIO_CREACION VARCHAR(50) NULL,	  -- 
	USUARIO_MODIFICACION VARCHAR(50) NULL,-- 
										  -- 
	VALOR_INICIAL DECIMAL(15,2) NULL,	  -- Valor Pago inicial cuando contrate el servicio
	VALOR DECIMAL(15,2) NOT NULL,		  -- Valor del pago 
	ACTIVO BIT NOT NULL,				  -- (0-Deshabilitada  1-Activa)
										  -- 
	FRECUENCIA_COBRO INT NOT NULL,		  -- Frecuencia de pago (1-Semanal, 2-Quincenal, 3-Mensual)
	PERIODO INT NOT NULL,				  -- Periodo anual para el cual esta vigente la cuenta 
	
	CONSTRAINT PK_SERVICIO_CUENTAS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_SERVICIO_CUENTAS_SERVICIO_ID FOREIGN KEY(SERVICIO_ID)   REFERENCES SERVICIOS(ID),
	CONSTRAINT FK_SERVICIO_CUENTAS_CLIENTE_ID FOREIGN KEY(CLIENTE_ID)   REFERENCES CLIENTES(ID)

)


CREATE TABLE DATOS_ADIC_SERVICIO
(
	ID INT NOT NULL,
	SERVICIO_CUENTA_ID INT NOT NULL,
	DESCRIPCION VARCHAR(350) NULL,
	UNIDAD_MEDIDA VARCHAR(50) NULL,
	VALOR_UNIDAD DECIMAL(15,2) NULL,
	FECHA_REGISTRO DATE NOT NULL,

	CONSTRAINT  PK_DATOS_ADIC_SERVICIO_ID  PRIMARY KEY(ID),
	CONSTRAINT FK_DATOS_ADIC_SERVICIO_SERVICIO_CUENTA_ID FOREIGN KEY(SERVICIO_CUENTA_ID) REFERENCES SERVICIO_CUENTAS(ID)
	
)






CREATE TABLE COBROS 
(
	ID INT NOT NULL,
	NUM_FACTURA VARCHAR(50) NOT NULL,
	SERVICIO_CUENTA_ID INT NOT NULL,
	CLIENTE_ID INT NOT NULL,
	
	FECHA_CREACION DATETIME NULL,		   
	FECHA_MODIFICACION DATETIME NULL,	   
	USUARIO_CREACION VARCHAR(50) NULL,	   
	USUARIO_MODIFICACION VARCHAR(50) NULL, 

	FECHA DATE NOT NULL,
	OBSERVACION VARCHAR(350) NULL,
	ACTIVO 	BIT NOT NULL

	CONSTRAINT PK_FACTURA_ID PRIMARY KEY(ID),
	CONSTRAINT FK_FACTURA_SERVICIO_CUENTA_ID FOREIGN KEY (SERVICIO_CUENTA_ID) REFERENCES SERVICIO_CUENTAS(ID)
)

GO 


CREATE TABLE COBRO_DETALLE
(
	ID BIGINT NOT NULL,
	COBRO_ID INT NOT NULL,
	CONCEPTO VARCHAR(100) NOT NULL,
	VALOR DECIMAL(15,2) NOT NULL,

	CONSTRAINT PK_COBRO_DETALLE_ID PRIMARY KEY(ID),
	CONSTRAINT FK_COBRO_DETALLE_COBRO_ID FOREIGN KEY(COBRO_ID) REFERENCES COBROS(ID)

)
GO 


CREATE TABLE METODO_PAGO 
(
	ID INT NOT NULL,
	DESCRIPCION VARCHAR(50),
	ACTIVO BIT NOT NULL

	CONSTRAINT PK_METODO_PAGO_ID PRIMARY KEY (ID)
)


CREATE TABLE RECIBOS
(
	ID INT NOT NULL,
	METODO_PAGO_ID INT NOT NULL,
	NUM_RECIBO INT NOT NULL,
	CLIENTE_ID INT NOT NULL,
	
	FECHA_CREACION DATETIME NULL,		   
	FECHA_MODIFICACION DATETIME NULL,	   
	USUARIO_CREACION VARCHAR(50) NULL,	   
	USUARIO_MODIFICACION VARCHAR(50) NULL, 

	FECHA DATE NOT NULL,
	OBSERVACION VARCHAR(350) NULL,
	ACTIVO 	BIT NOT NULL

	CONSTRAINT PK_RECIBOS PRIMARY KEY(ID),
	CONSTRAINT FK_RECIBOS_METODO_PAGO_ID FOREIGN KEY(METODO_PAGO_ID) REFERENCES METODO_PAGO(ID)
)

GO 




CREATE TABLE RECIBO_DETALLE
(
	ID BIGINT NOT NULL,
	RECIBO_ID INT NOT NULL,
	COBRO_DETALLE_ID BIGINT NOT NULL,
	
	CONSTRAINT PK_RECIBO_DETALLE_ID PRIMARY KEY(ID),
	CONSTRAINT FK_RECIBO_DETALLE__RECIBO_ID FOREIGN KEY (RECIBO_ID) REFERENCES RECIBOS(ID),
	CONSTRAINT FK_RECIBO_DETALLE__COBRO_DETALLE_ID FOREIGN KEY (COBRO_DETALLE_ID) REFERENCES COBRO_DETALLE(ID),

)



CREATE TABLE PARAMETROS_SISTEMA
(
	ID INT NOT NULL,
	PERIODO INT NOT NULL,
	PORC_DESCUENTO_PAGO_ADELANT DECIMAL(15,4) NULL,
	PORC_RECARCAGOS_MORA DECIMAL(15,4) NULL,
	CANT_PAGO_ADELAN INT NULL
)